### ISSUE TITLE
table width = 100%

### ISSUE THREAD

**Issue by taxist08** [Lansoweb/LosPdf#1]
Hi friend!
Add pls. avalable options in MpdRenderer class

```
$mpdf->keep_table_proportions = true;
```

**Comment by Lansoweb** [comment]
In your controller (or anywhere else) you can set any mPdf option, for example:

``` php
$renderer = $this->getServiceLocator()->get('ViewPdfRenderer');
$renderer->getEngine()->keep_table_proportions = true;
$renderer->getEngine()->DefHTMLFooterByName('Footer', 'Page {PAGENO}');
```

Since this parameter is not true per default in the mPdf library, i think we should not set this here.

**Comment by taxist08** [comment]
Thank you very much, it worked out!

**Comment by Lansoweb** [comment]
My pleasure. Thanks for using!

**Comment by taxist08** [comment]
Still, I need to get the result in a string
etc:        return $mpdf->Output('','S');

**Comment by Lansoweb** [comment]
You can do:

``` php
$pdf = new PdfModel();
$renderer = $this->getServiceLocator()->get('ViewPdfRenderer');
$pdf->setTerminal(true);
$pdf->setOption("paperSize", "a4");

$pdf->setTemplate('site/index/pdf'); // template to the view file
$html = $renderer->getRenderer()->render($pdf);
$renderer->getEngine()->WriteHTML($html);
$out = $renderer->getEngine()->Output('','S');
```

**Comment by taxist08** [comment]
Ok!!!

**Comment by Lansoweb** [comment]
But i will add a method to return the string from the renderer, so the code will be resumed to 1 or 2 lines. In the meantime, use the workaround above. Thanks!

**Comment by Lansoweb** [comment]
@taxist08 I've updated the module and now you can render the pdf to string and file. Check the README for usage. Thanks!

**Comment by taxist08** [comment]
Thank you Leandro Silva!!!
