### ISSUE TITLE
Optionnames as constants

### ISSUE THREAD

**Issue by gartner** [Lansoweb/LosPdf#3]
I think it would be nice to have the names of options to set, using setOption(), instead of using strings:

$pdfModel->setOption(PdfModel::paperSize, 'A4');
$pdfModel->setOption(PdfModel::paperOrientation, 'landscape');
- this would let your IDE autocomplete the options, and possibly avoid some errors. 

Any thoughts? I could have a go at implementing it, if other people like the idea too.

**Comment by Lansoweb** [comment]
Nice, but i'd go further:

``` php
$pdfModel->setOption(PdfModel::PAPER_SIZE, PdfModel::SIZE_A4);
$pdfModel->setOption(PdfModel::PAPER_ORIENTATION, PdfModel::ORIENTATION_LANDSCAPE);
```

**Comment by Lansoweb** [comment]
Done in release 1.0.0.
