### ISSUE TITLE
ViewManager::getResolver()

### ISSUE THREAD

**Issue by andrearruda82** [Lansoweb/LosPdf#5]
Esta estourando um erro:

> Fatal error: Call to undefined method Zend\Mvc\View\Http\ViewManager::getResolver() in D:\dev\oceania\procuracao\www\vendor\los\lospdf\src\LosPdf\Model\ViewPdfRenderer.php on line 32

Como se pode ver o problema esta no ViewManager::getResolver() e acredito que tb no ViewManager::getRenderer().

**Comment by andrearruda82** [comment]
Fiz um ajuste e passou:

**ANTES**

> public function createService(ServiceLocatorInterface $serviceLocator)
> {
>   $viewManager = $serviceLocator->get('ViewManager');
> 
>   $pdfRenderer = new MpdfRenderer();
>   $pdfRenderer->setResolver($viewManager->getResolver());
>   $pdfRenderer->setRenderer($viewManager->getRenderer());
> 
>   return $pdfRenderer;
> }

**DEPOIS**

> public function createService(ServiceLocatorInterface $serviceLocator)
> {
>   /\* @var $viewRenderer \Zend\View\Renderer\PhpRenderer */
>   $viewRenderer = $serviceLocator->get('ViewRenderer');
> 
>   /\* @var $viewResolver \Zend\View\Resolver\AggregateResolver */
>   $viewResolver = $serviceLocator->get('ViewResolver');
> 
>   $pdfRenderer = new MpdfRenderer();
>   $pdfRenderer->setResolver($viewResolver);
>   $pdfRenderer->setRenderer($viewRenderer);
> 
>   return $pdfRenderer;
> }

**Comment by Lansoweb** [comment]
Olá @andrearruda . Obrigado pela informação. Vários módulo do Zend Framework 2 sofreram algumas alterações para a versão 3 e acabam gerando alguma incompatibilidade. Vou limitar a versão atual do módulo para antes da versão 2.7 e criar uma nova versão para as recentes.

**Comment by Lansoweb** [comment]
Ajustado em https://github.com/Lansoweb/LosPdf/commit/b8a9bb8110fd109d4b000c3d04bf5bbccfda6f0d e gerada nova versão https://github.com/Lansoweb/LosPdf/releases/tag/1.0.1
