### ISSUE TITLE
It works fine on localhost, when I move all the software in to a server it fails

### ISSUE THREAD

**Issue by JorgeBorda** [Lansoweb/LosPdf#7]
It is working very well the module / library in zf2 in a localhost under windows, when move to production givme the following error:
-------------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/25769249/26673455/3f6ba0fe-46bd-11e7-8c16-88cb167e6676.png)

-------------------------------------------------------------------------
I suppose it's due to lack of definition of something ???... any error in the configuration server????
a lot of thanks..
Jorge

**Comment by Lansoweb** [comment]
Hi @JorgeBorda, did you include de Module in your application? Because the factory for ViewPdfRenderer is included in the config/module.config.php.

**Comment by JorgeBorda** [comment]
this is my  config/module.config.php
`<?php
/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2015 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace Application;

return array(
    'router' => array(
        'routes' => array(
            'home' => array(
                'type' => 'Zend\Mvc\Router\Http\Literal',
                'options' => array(
                    'route'    => '/',
                    'defaults' => array(
                        'controller' => 'Application\Controller\Index',
                        'action'     => 'index',
                    ),
                ),
            ),
            // The following is a route to simplify getting started creating
            // new controllers and actions without needing to create a new
            // module. Simply drop new controllers in, and you can access them
            // using the path /application/:controller/:action
            'application' => array(
                'type'    => 'Literal',
                'options' => array(
                    'route'    => '/application',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Application\Controller',
                        'controller'    => 'Index',
                        'action'        => 'index',
                    ),
                ),
                'may_terminate' => true,
                'child_routes' => array(
                    'default' => array(
                        'type'    => 'Segment',
                        'options' => array(
                            'route'    => '/[:controller[/:action]]',
                            'constraints' => array(
                                'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                                'action'     => '[a-zA-Z][a-zA-Z0-9_-]*',
                            ),
                            'defaults' => array(
                            ),
                        ),
            ),	),	),
            "login" => array(
        		"type" => "Segment",
        		'options' => array(
        			'route' => '/login',
        			'defaults' => array(
        				'__NAMESPACE__' => 'Application\Controller',
        				'controller' => 'Login',
        				'action' => 'index',
        	),	),	),
        	'repostajes' => array(
        		'type' => 'Segment',
        		'options' => array(
        			'route' => '/repostajes[/[:action][/:id]]',
        			'constraints' => array(
        				'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
        				'id' => '[0-9]*',
        			),
        			'defaults' => array(
        				'__NAMESPACE__' => 'Application\Controller',
        				'controller' => 'Repostajes',
        				'action' => 'index',
        	),	),	),
        	'exportarcsv' => array(
        		'type' => 'Segment',
        		'options' => array(
       				'route' => '/exportarcsv[/[:action]]',
       				'constraints' => array(
   						'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
       				),
       				'defaults' => array(
						'__NAMESPACE__' => 'Application\Controller',
						'controller' => 'Exportarcsv',
						'action' => 'index',
        	),	),	),
        	**'infopdfdetalle' => array(
        		'type' => 'Segment',
        		'options' => array(
        				'route' => '/infopdfdetalle[/[:action]]',
        				'constraints' => array(
        						'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
        				),
        				'defaults' => array(
        						'__NAMESPACE__' => 'Application\Controller',
        						'controller' => 'Infopdfdetalle',
        						'action' => 'index',
        	),	),	),
        	'infopdfservicio' => array(
        		'type' => 'Segment',
        		'options' => array(
        				'route' => '/infopdfservicio[/[:action]]',
        				'constraints' => array(
        						'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
        				),
        				'defaults' => array(
        						'__NAMESPACE__' => 'Application\Controller',
        						'controller' => 'Infopdfservicio',
        						'action' => 'index',
        	),	),	),**
        ),
    ),
	'service_manager' => array(
		'abstract_factories' => array(
			'Zend\Cache\Service\StorageCacheAbstractServiceFactory',
			'Zend\Log\LoggerAbstractServiceFactory',
			
		),
		'factories' => array(
			'translator' => 'Zend\Mvc\Service\TranslatorServiceFactory',
		),
		'invokables' => array(
			"Zend\Authentication\AuthenticationService" => "Zend\Authentication\AuthenticationService"
		)
	),
	'translator' => array(
        'locale' => 'es_ES',
        'translation_file_patterns' => array(
            array(
                'type'     => 'gettext',
                'base_dir' => __DIR__ . '/../language',
                'pattern'  => '%s.mo',
            ),
        ),
    ),
    'controllers' => array(
        'invokables' => array(
        	'Application\Controller\Index' => Controller\IndexController::class,
        	'Application\Controller\Login' => Controller\LoginController::class,
        	'Application\Controller\Repostajes' => Controller\RepostajesController::class,
        	'Application\Controller\Exportarcsv' => Controller\ExportarcsvController::class,
        	**'Application\Controller\Infopdfdetalle' => Controller\InfopdfdetalleController::class,
        	'Application\Controller\Infopdfservicio' => Controller\InfopdfservicioController::class,**
        ),
    ),
	"controller_plugins" => array(
			'invokables' => array(
					'Plugins' => "Application\Controller\Plugin\Plugins",
			),
	),
	'view_manager' => array(
        'display_not_found_reason' => true,
        'display_exceptions'       => true,
        'doctype'                  => 'HTML5',
        'not_found_template'       => 'error/404',
        'exception_template'       => 'error/index',
        'template_map' => array(
            'layout/layout'           => __DIR__ . '/../view/layout/layout.phtml',
            'application/index/index' => __DIR__ . '/../view/application/index/index.phtml',
            'error/404'               => __DIR__ . '/../view/error/404.phtml',
            'error/index'             => __DIR__ . '/../view/error/index.phtml',
        	'admin/layout' => __DIR__ . '/../view/layout/admin.phtml',
        	'login/layout' => __DIR__ . '/../view/layout/login.phtml',
        	'logout/layout' => __DIR__ . '/../view/layout/logout.phtml',
	        'partial/navbar' => __DIR__ . '/../view/layout/partial/navbar.phtml',
        ),
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),
	'view_helpers' => array(
		'invokables' => array(
			'lowercase' => 'Application\View\Helper\LowerCase',
		),
	),
	// Placeholder for console routes
    'console' => array(
        'router' => array(
            'routes' => array(
            ),
        ),
    ),
);
`
what and where have i insert ????

**Comment by JorgeBorda** [comment]
OK thanks...

**Comment by JorgeBorda** [comment]
yes.... i forgot... in config/module.config.php.
'view_manager' => [
        'strategies' => [
            'ViewPdfStrategy',
        ],
    ],
    'service_manager' => [
        'factories' => [
            'ViewPdfRenderer' => 'LosPdf\Model\ViewPdfRenderer',
            'ViewPdfStrategy' => 'LosPdf\Model\ViewPdfStrategy',
        ],
    ],
thanks...

**Comment by JorgeBorda** [comment]
any way.... if I use this code is working:
```
			////////////  PDF To file
			$pdf = new PdfModel();
			$renderer = $this->getServiceLocator()->get('ViewPdfRenderer');
		
			//  termino de poner variables	
				
			$renderer->getEngine()->setHTMLHeader('
				<table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt; color: #000000; font-weight: bold; font-style: italic; border-bottom: 1px solid #000">
					<caption>Sistema de Gestión de Combustible</caption>
					<tr>
						<td width="35%"><h2>Listado de Repostajes</h2></td>
						<td width="40%" align="center" style="font-weight: bold; "><h3>Servicio: '. $nomServicio .'<br>Matricula: '. $this->session->FILTRO_MATRICULA.'</h3></td>
						<td width="25%" align="center" style="font-weight: bold; ">Fecha Desde: '. $sFILTRO_FECHA_DESDE .'<br>Fecha Hasta: '. $sFILTRO_FECHA_HASTA.'</td>
					</tr>
				</table>');
				
			$renderer->getEngine()->setHTMLFooter(
				'<table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt; color: #000000; font-weight: bold; font-style: italic; border-top: 1px solid #000">
					<tr>
						<td width="50%" style="text-align: left; font-weight: bold; font-style: italic;">'. $fechaInforme .'</td>
						<td width="50%" style="text-align: right; ">Página: {PAGENO}</td>
					</tr>
				</table>');

			$pdf->setTerminal(true);
			$pdf->setVariables(['tablas' => $datosArray, 'resumen' => $datosArray2]);
			$pdf->setOption('paperSize', 'a4'); // Defaults to "8x11"
			$pdf->setOption('paperOrientation', 'portrait'); // Defaults to "portrait" landscape
			
			return $pdf;
```
But if I add this lines before return  have a big error
```
 // the same code of above...
			$pdf->setTemplate('Application/Repostajes/infopdfdetalle');
			$renderer->renderToFile($pdf, 'C:\xampp\htdocs\combustibles\public\tmp\Repostaje' . $this->session->FILTRO_MATRICULA .'.pdf');
                        return $pdf;
```
the error is 
```
Fatal error: Uncaught exception 'Zend\View\Exception\RuntimeException' with message 'Zend\View\Renderer\PhpRenderer::render: Unable to render template "Application/Repostajes/infopdfdetalle"; resolver could not resolve to a file' in /var/www/clients/client1/web6/web/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php:497 
Stack trace: #0 /var/www/clients/client1/web6/web/vendor/los/lospdf/src/LosPdf/View/Renderer/MpdfRenderer.php(41): Zend\View\Renderer\PhpRenderer->render(Object(LosPdf\View\Model\PdfModel), NULL) 
#1 /var/www/clients/client1/web6/web/vendor/los/lospdf/src/LosPdf/View/Renderer/AbstractRenderer.php(53): LosPdf\View\Renderer\MpdfRenderer->doPrepare(Object(LosPdf\View\Model\PdfModel), NULL) 
#2 /var/www/clients/client1/web6/web/vendor/los/lospdf/src/LosPdf/View/Renderer/AbstractRenderer.php(59): LosPdf\View\Renderer\AbstractRenderer->prepare(Object(LosPdf\View\Model\PdfModel), NULL) 
#3 /var/www/clients/client1/web6/web/vendor/zendframework/zend-view/src/View.php(207): LosPdf\View\Renderer\AbstractRender in /var/www/clients/client1/web6/web/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php on line 497
```
----------------------------------------------------------

and the file Application/Repostajes/infopdfdetalle.phtml exists

**Comment by JorgeBorda** [comment]
Thanks, Noy is working..  a lot of thanks…

 

Jorge

 

De: Leandro Silva [mailto:notifications@github.com] 
Enviado el: viernes, 2 de junio de 2017 14:19
Para: Lansoweb/LosPdf
CC: JorgeBorda; Mention
Asunto: Re: [Lansoweb/LosPdf] It works fine on localhost, when I move all the software in to a server it fails (#7)

 

Hi @JorgeBorda <https://github.com/jorgeborda> , did you include de Module in your application? Because the factory for ViewPdfRenderer is included in the config/module.config.php.

**Comment by Lansoweb** [comment]
You're welcome! Thanks.
